CREATE TABLE User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0,
    Draws INT NOT NULL DEFAULT 0,
    Rating INT NOT NULL DEFAULT 1200,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GameType (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description TEXT,
    MinPlayers INT NOT NULL,
    MaxPlayers INT NOT NULL,
    BoardRows INT NOT NULL,
    BoardCols INT NOT NULL
);

CREATE TABLE GameSession (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GameTypeID INT NOT NULL,
    Player1ID INT NOT NULL,
    Player2ID INT NOT NULL,
    Status ENUM('ACTIVE','FINISHED','ABANDONED') NOT NULL DEFAULT 'ACTIVE',
    CurrentTurnUserID INT,
    TurnStartedAt DATETIME,
    WinnerID INT,
    BoardState TEXT,
    StartTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EndTime DATETIME,
    RematchSessionID INT,
    FOREIGN KEY (GameTypeID) REFERENCES GameType(ID),
    FOREIGN KEY (Player1ID) REFERENCES User(ID),
    FOREIGN KEY (Player2ID) REFERENCES User(ID),
    FOREIGN KEY (CurrentTurnUserID) REFERENCES User(ID),
    FOREIGN KEY (WinnerID) REFERENCES User(ID),
    FOREIGN KEY (RematchSessionID) REFERENCES GameSession(ID)
);

CREATE TABLE Move (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    MoveNumber INT NOT NULL,
    Payload TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_move_session_number (SessionID, MoveNumber),
    FOREIGN KEY (SessionID) REFERENCES GameSession(ID),
    FOREIGN KEY (UserID) REFERENCES User(ID)
);

CREATE TABLE MatchmakingQueue (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    GameTypeID INT NOT NULL,
    Status ENUM('WAITING','MATCHED','CANCELLED') NOT NULL DEFAULT 'WAITING',
    JoinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(ID),
    FOREIGN KEY (GameTypeID) REFERENCES GameType(ID)
);

CREATE TABLE ChatMessage (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES GameSession(ID),
    FOREIGN KEY (UserID) REFERENCES User(ID)
);

INSERT INTO GameType (Name, Description, MinPlayers, MaxPlayers, BoardRows, BoardCols)
VALUES ('Checkers', 'Classic two-player checkers on an 8x8 board.', 2, 2, 8, 8);

CREATE DATABASE IF NOT EXISTS matchmaker_test;
GRANT ALL PRIVILEGES ON matchmaker_test.* TO 'matchmaker'@'%';
FLUSH PRIVILEGES;
USE matchmaker_test;

CREATE TABLE User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0,
    Draws INT NOT NULL DEFAULT 0,
    Rating INT NOT NULL DEFAULT 1200,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GameType (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description TEXT,
    MinPlayers INT NOT NULL,
    MaxPlayers INT NOT NULL,
    BoardRows INT NOT NULL,
    BoardCols INT NOT NULL
);

CREATE TABLE GameSession (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GameTypeID INT NOT NULL,
    Player1ID INT NOT NULL,
    Player2ID INT NOT NULL,
    Status ENUM('ACTIVE','FINISHED','ABANDONED') NOT NULL DEFAULT 'ACTIVE',
    CurrentTurnUserID INT,
    TurnStartedAt DATETIME,
    WinnerID INT,
    BoardState TEXT,
    StartTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EndTime DATETIME,
    RematchSessionID INT,
    FOREIGN KEY (GameTypeID) REFERENCES GameType(ID),
    FOREIGN KEY (Player1ID) REFERENCES User(ID),
    FOREIGN KEY (Player2ID) REFERENCES User(ID),
    FOREIGN KEY (CurrentTurnUserID) REFERENCES User(ID),
    FOREIGN KEY (WinnerID) REFERENCES User(ID),
    FOREIGN KEY (RematchSessionID) REFERENCES GameSession(ID)
);

CREATE TABLE Move (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    MoveNumber INT NOT NULL,
    Payload TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_move_session_number (SessionID, MoveNumber),
    FOREIGN KEY (SessionID) REFERENCES GameSession(ID),
    FOREIGN KEY (UserID) REFERENCES User(ID)
);

CREATE TABLE MatchmakingQueue (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    GameTypeID INT NOT NULL,
    Status ENUM('WAITING','MATCHED','CANCELLED') NOT NULL DEFAULT 'WAITING',
    JoinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(ID),
    FOREIGN KEY (GameTypeID) REFERENCES GameType(ID)
);

CREATE TABLE ChatMessage (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES GameSession(ID),
    FOREIGN KEY (UserID) REFERENCES User(ID)
);
